### ISSUE TITLE
ROADMAP

### ISSUE THREAD

**Issue by Gadgetoid** [Gadgetoid/pgfutil#1]
* [ ] Command-line interface for converting fonts between various data types
* [ ] C header (.h) file support - outputs a bitmap font C struct
* [ ] Python code (.py) file support - outputs a byte array
* [ ] Better UX with some config
* [ ] Actual tests! See how 32blit tools do it.
* [ ] Port font packing/unpacking code to Construct, maybe, seems right up its alley
* [ ] Endpoints for GUI / CLI
